class Suggestions {
  static final List<String> suggestionlist = [
    'What is phishing?',
    'How can you identify a phishing email?',
    'What is malware?',
    'How can you protect against malware?',
    'What is a firewall?',
    'Why is encryption important for data security?',
    'What is cybersecurity?',
    'What is a vulnerability?',
    'What is a patch?',
    'What is two-factor authentication (2FA)?',
    'What is a DDoS attack?',
    'How can you prevent DDoS attacks?',
    'What is social engineering?',
    'What are some common social engineering techniques?',
    'What is ransomware?',
    'How can you protect against ransomware attacks?',
    'What is a firewall?',
    'What is a VPN (Virtual Private Network)?',
    'What is a vulnerability scan?',
    'What is penetration testing (pen testing)?',
    'What is the principle of least privilege?',
    'What is encryption?',
    'What is a data breach?',
    'What is multi-factor authentication (MFA)?',
    'What is endpoint security?',
    'What is identity theft?',
    'What is a man-in-the-middle (MITM) attack?',
    'What is a brute-force attack?',
    'What is phishing?',
    'What is spear phishing?',
    'What is malware?',
    'What is ransomware?',
    'What is a denial-of-service (DoS) attack?',
    'What is a distributed denial-of-service (DDoS) attack?',
    'What is encryption?',
    'What is network segmentation?',
    'What is a zero-day exploit?',
    'What is data encryption in transit?',
    'What is data encryption at rest?',
    'What is a cybersecurity incident response plan?',
    'What is security awareness training?',
    'What is a security policy?',
    'What is a security incident?',
    'What is a security risk assessment?',
    'What is a security control?',
    'What is a security incident response team (SIRT)?',
    'What is security information and event management (SIEM)?',
    'What is network access control (NAC)?',
    'What is a security incident response plan?',
    'What is threat intelligence?',
    'What is a security audit?',
    'What is secure coding?',
    'What is a security incident response tabletop exercise?',
    'What is a bug bounty program?',
    'What is a security information sharing platform?',
    'What is a security incident classification and prioritization framework?',
    'What is security information and event management (SIEM)?',
    'What is network segmentation?',
    'What is an intrusion detection system (IDS)?',
    'What is a security incident response plan?',
    'What is encryption?',
    'What is a data breach?',
    'What is a firewall?',
    'What is penetration testing (pen testing)?',
    'What is multi-factor authentication (MFA)?',
    'What are the common Cyberattacks?',
    'What are the elements of cyber security?',
    'Lost access to email address or phone number linked to Instagram account?',
    'Try to regain your access to your gmail account?',
    'How do I manage logging in with accounts in Accounts Centre?',
    'Disabled Instagram account',
    'Recover your Instagram password',
    'What you can do if your email address can\'t be found during a password reset for your Instagram account',
    'What to do if your Instagram account posts unauthorized content',
    'I can\'t log in',
    'Securing your Instagram account with two-factor authentication',
    'Instagram accounts memorialized by mistake',
    'Hacked Instagram account',
    'If you think that your Instagram account has been hacked',
    'Hate accounts',
    'Enable connected experiences across your accounts in an Accounts Centre',
    'Adding accounts',
    'Links in password reset email from Instagram aren\'t working',
    'What to do if the email address for your Instagram account was changed',
    'If you receive a "Welcome to Instagram" email but didn\'t create an account',
    'Does two-factor authentication still work on Instagram accounts that I\'ve linked to a single login?',
    'Why you\'re receiving a password reset email for the wrong Instagram account',
    'About using one login for multiple Instagram accounts',
    'What you can do if your login info is already used by another Instagram account',
    'IT Policies',
    'How do I protect my computer from malware?',
    'What is phishing and how can I avoid it?',
    'How do I create a strong password?',
    'What is two-factor authentication?',
    'How can I protect my online accounts?',
    'What should I do if my computer is infected?',
    'How can I secure my home Wi-Fi network?',
    'What is ransomware and how can I prevent it?',
    'How can I protect my sensitive information online?',
    'What should I do if I receive a suspicious email?',
    'How can I prevent identity theft?',
    'How do I recover my forgotten password?',
    'What steps can I take if I\'ve lost access to my recovery email?',
    'Is it possible to recover my account if I\'ve forgotten my username?',
    'Can I recover my account if I\'ve lost my phone and don\'t have access to recovery codes?',
    'What should I do if my account has been compromised and I can\'t log in?',
    'How can I regain access to my account if I\'ve forgotten the answers to my security questions?',
    'Is there a way to recover my account if I no longer have access to the phone number associated with it?',
    'How long does the account recovery process usually take?',
    'What information do I need to provide for successful account recovery?',
    'Are there any alternative methods for account recovery if I can\'t access my email or phone?',
    'Can I recover my account if I\'ve been locked out due to too many failed login attempts?',
    'How can I prove my identity for account recovery purposes?',
    'Is it possible to recover an account if I\'ve deleted the associated email address?',
    'What should I do if my account recovery request has been denied?',
    'Are there any specific security measures I can take to prevent future account recovery issues?',
    'What is phishing?',
    'How can I protect myself from phishing attacks?',
    'What is malware?',
    'How can I prevent malware infections?',
    'What is two-factor authentication (2FA)?',
    'How does encryption enhance security?',
    'What is a firewall?',
    'How can I secure my Wi-Fi network?',
    'What is a DDoS attack?',
    'How can I protect against DDoS attacks?',
    'What is social engineering?',
    'How can I recognize social engineering attacks?',
    'What is ransomware?'
        'What is social media?',
    'What are some popular social media platforms?',
    'How does social media affect society?',
    'What are some benefits of using social media?',
    'What are some risks of using social media?',
    'How can businesses use social media effectively?',
    'How can individuals protect their privacy online?',
    'How can businesses measure their social media ROI?',
    'What is influencer marketing?',
    'How can individuals build a personal brand on social media?',
    'What are some strategies for increasing engagement on social media?',
    'How can businesses handle negative feedback on social media?',
    'What are some emerging trends in social media?',
    'How can parents monitor and guide their children\'s social media use?',
    'What are some ethical considerations in social media marketing?',
    'How can social media be used for social activism and advocacy?',
    'What are the differences between organic and paid social media content?',
    'How can businesses use social listening to inform their strategy?',
    'What are some best practices for creating visually appealing content on social media?',
    'How can businesses leverage user-generated content (UGC) on social media?',
    'What are some key metrics to track on social media?',
    'How can businesses effectively manage multiple social media accounts?',
    'What are some common social media advertising formats?',
    'How can businesses use social media for customer service?',
    'What are the legal considerations for businesses using social media?',
    'How can businesses use social media for market research?',
    'What are some strategies for building a strong social media community?',
    'How can individuals and businesses deal with social media algorithm changes?',
    'What are some tips for creating an effective social media content calendar?',
    'How can businesses leverage social media for employee advocacy?',
    'What are the benefits of using social media for job recruitment?',
    'How can businesses leverage social media influencers for marketing campaigns?',
    'What are some strategies for increasing organic reach on social media?',
    'How can businesses use social media for crisis communication?',
    'What are some ways to effectively integrate social media into an omnichannel marketing strategy?',
    'How can businesses leverage user engagement data to improve social media strategy?',
    'What are some tips for maintaining authenticity and building trust on social media?',
    'How can businesses use social media for lead generation and conversion?',
    'How can businesses leverage social media for brand storytelling?',
    'What are some strategies for maximizing engagement during live social media events?',
    'How can businesses effectively measure the impact of social media marketing efforts?',
    'What are some strategies for building a strong personal brand on social media?',
    'How can businesses effectively handle social media crises and negative publicity?',
    'How can businesses leverage social media for employee advocacy?',
    'How can businesses leverage user-generated content (UGC) in their social media marketing strategies?',
    'What are some strategies for building an effective social media content strategy?',
    'How can businesses use social media to drive website traffic and increase conversions?',
    'What are some emerging trends in social media marketing?',
    'How can businesses effectively use social media for customer retention and loyalty?',
    'How can businesses effectively leverage social media for influencer partnerships?',
    'What are some strategies for businesses to effectively engage with their audience on social media?',
    'How can businesses use social media analytics to inform their marketing strategy?',
    'How can businesses use social media to showcase their company culture and attract top talent?',
    'What are some best practices for businesses to effectively manage their social media presence and reputation?',
    'How can businesses effectively use social media for customer feedback and market research?',
    'What are some strategies for businesses to leverage social media for crisis prevention and management?',
    'How can businesses use social media to foster customer loyalty and advocacy?',
    'How can businesses effectively measure the ROI of their social media marketing efforts?',
    'How can businesses effectively integrate social media into their overall marketing strategy?',
    'What is a data breach, and how can it affect social media users?',
    'What are the privacy risks associated with location-based services on social media platforms?',
    'How do social media platforms protect user data from unauthorized access and cyber attacks?',
    'What steps can users take to enhance the security of their social media profiles?',
    'What are some common social engineering tactics used to manipulate users on social media?',
    'How can businesses use social media to educate their employees about cybersecurity best practices?',
    'What are the potential consequences of a social media account takeover for businesses and individuals?',
    'How can users verify the authenticity of information shared on social media platforms?',
    'How do I recover my Instagram account if I forgot my password?',
    'What should I do if I can\'t remember the email or phone number linked to my Instagram account?',
    'How long does it take for Instagram to respond to an account recovery request?',
    'Can I recover my Instagram account if it was hacked or disabled?',
    'What information do I need to provide for Instagram account recovery?',
    'How can I prevent my Instagram account from being compromised in the future?',
    'What should I do if my Instagram account was disabled for violating community guidelines?',
    'Can I recover my Instagram account if I deleted it voluntarily?',
    'How do I contact Instagram support for account recovery assistance?',
    'Can I recover my Instagram account if I no longer have access to the email or phone number linked to it?',
    'How can I recover my Instagram account if I no longer have access to the phone number used for two-factor authentication?',
    'Can I recover my Instagram account if I forgot the email address associated with it?',
    'What should I do if my Instagram account was hacked and the email associated with it was changed?',
    'Can I recover my Instagram account if it was permanently deleted?',
    'How do I prove ownership of my Instagram account for account recovery purposes?',
    'What steps should I take to secure my Instagram account after recovering it from a hacking incident?',
    'How can I retrieve deleted messages or photos from my Instagram account?',
    'What should I do if my Instagram account is repeatedly targeted by hackers or phishing attempts?',
    'Can I recover my Instagram account if it was disabled due to copyright infringement or intellectual property violations?',
    'How do I verify my identity for Instagram account recovery if I don\'t have a government-issued ID?',
    'Can I recover my Instagram account if it was disabled for violating community guidelines multiple times?',
    'How do I recover my Instagram account if I no longer have access to the recovery email or phone number?',
    'Is it possible to recover a hacked Instagram account without contacting Instagram support?',
    'What should I do if my Instagram account is compromised and used for malicious purposes?',
    'Can I recover my Instagram account if it was deactivated due to inactivity?',
    'How do I recover my Instagram account if it\'s linked to a Facebook account that I no longer have access to?',
    'What steps should I take to prevent my Instagram account from being compromised in the future?',
    'Can I recover my Instagram account if it was mistakenly reported and disabled by other users?',
    'How do I recover my Instagram account if I\'m unable to verify my identity using the provided methods?',
    'Is it possible to recover a deleted Instagram account after the 30-day grace period?',
    'Can I recover my Instagram account if I don\'t remember the username or email associated with it?',
    'What should I do if my Instagram account is compromised and I suspect that my personal information has been accessed?',
    'How do I recover my Instagram account if I\'m unable to receive the verification code for two-factor authentication?',
    'Can I recover my Instagram account if it was disabled due to a mistaken copyright infringement claim?',
    'How do I recover my Instagram account if I can\'t access the email or phone number used for verification?',
    'What should I do if my Instagram account was disabled for violating community guidelines, but I believe it was a mistake?',
    'Can I recover my Instagram account if it was disabled due to suspicious activity or security concerns?',
    'How long does it take for Instagram to review an account recovery request?',
    'Can I recover my Instagram account if I no longer have access to the device used for two-factor authentication?',
    'What should I do if my Instagram account was disabled due to a mistaken identity or impersonation report?',
    'How do I recover my Instagram account if I suspect it was hacked and my password was changed?',
    'Can I recover my Instagram account if I forgot the password and no longer have access to the email address used for verification?',
    'How can I regain access to my Instagram account if it was temporarily locked for security reasons?',
    'Can I recover my Instagram account if it was disabled due to a mistaken report of underage registration?',
    'How do I recover my Instagram account if I can\'t remember the username or password and no longer have access to the email or phone number associated with it?',
    'What should I do if my Instagram account was disabled due to a violation of copyright or trademark laws?',
    'Can I recover my Instagram account if it was disabled due to a violation of the platform\'s terms of service?',
    'How do I recover my Instagram account if it was hacked and the hacker changed the recovery information?',
    'How can I recover my WhatsApp account if I forgot my password?',
    'Can I recover my WhatsApp account if I lost my phone or SIM card?',
    'What should I do if my WhatsApp account is hacked?',
    'How do I recover my WhatsApp account if I can\'t receive the verification code?',
    'Can I recover my WhatsApp account if I deleted the app?',
    'How do I recover my WhatsApp account if I forgot my email associated with it?',
    'What should I do if I forgot my WhatsApp account\'s PIN?',
    'Can I recover my WhatsApp account if I changed my phone number?',
    'How long does it take to recover a WhatsApp account?',
    'Can I recover my WhatsApp account if it\'s banned?',
    'How do I recover my WhatsApp account if I switched to a new phone with a different operating system (e.g., Android to iPhone or vice versa)?',
    'Can I recover my WhatsApp account if I forgot my account\'s linked email address or phone number?',
    'What steps should I take if my WhatsApp account is temporarily suspended?',
    'How do I recover my WhatsApp account if I accidentally deleted my chat history?',
    'Can I recover my WhatsApp account if I don\'t remember my account\'s security PIN?',
    'How can I recover my WhatsApp account if I\'m not receiving the verification code via SMS or call?',
    'What should I do if my WhatsApp account is permanently banned?',
    'Can I recover my WhatsApp account if I uninstalled the app and forgot to back up my chat history?',
    'How do I recover my WhatsApp account if I can\'t access the email or phone number associated with it?',
    'Can I recover my WhatsApp account if it\'s hacked and the hacker changed my phone number?',
    'How do I recover my WhatsApp account if I lost my device and didn\'t back up my chat history?',
    'Can I recover my WhatsApp account if I forgot my two-step verification code?',
    'What should I do if my WhatsApp account is locked due to suspicious activity?',
    'How can I recover my WhatsApp account if I can\'t remember my account\'s security PIN?',
    'Can I recover my WhatsApp account if I didn\'t link an email address or phone number to it?',
    'How do I recover my WhatsApp account if I changed my phone and forgot to transfer my chat backup?',
    'What steps should I take if I received a notification that my WhatsApp account is being used on another device?',
    'Can I recover my WhatsApp account if I lost access to both my phone number and email address?',
    'How do I recover my WhatsApp account if I\'m not receiving the verification code despite entering the correct phone number?',
    'What should I do if my WhatsApp account is blocked by WhatsApp due to a violation of their terms of service?',
    'How can I recover my WhatsApp account if I no longer have access to the phone number associated with it?',
    'Can I recover my WhatsApp account if I forgot my account\'s linked email address and phone number?',
    'What should I do if my WhatsApp account is disabled due to a violation of WhatsApp\'s terms of service?',
    'How do I recover my WhatsApp account if I forgot my account\'s linked email address and security PIN?',
    'Can I recover my WhatsApp account if it was hacked and the hacker changed the associated phone number?',
    'What steps should I take if I suspect my WhatsApp account has been compromised?',
    'How do I recover my WhatsApp account if I forgot my two-step verification code and lost access to the email address associated with it?',
    'Can I recover my WhatsApp account if it was deleted by mistake?',
    'How do I recover my WhatsApp account if I forgot the security PIN?',
    'What should I do if my WhatsApp account is suspended due to suspicious activity?',
    'How can I recover my WhatsApp account if I forgot both my phone number and email address?',
    'Can I recover my WhatsApp account if I didn\'t set up two-step verification?',
    'What should I do if I suspect my WhatsApp account has been compromised and I can\'t access it?',
    'How do I recover my WhatsApp account if I\'m unable to receive SMS or calls for verification?',
    'Can I recover my WhatsApp account if I forgot the s to my security s?',
    'What steps should I take if my WhatsApp account is temporarily banned?',
    'How do I recover my WhatsApp account if it was deleted due to inactivity?',
    'Can I recover my WhatsApp account if I deleted it intentionally but changed my mind?',
    'What should I do if my WhatsApp account is banned and I believe it was a mistake?',
    'How do I recover my WhatsApp account if I forgot my account\'s password and linked email address?',
    'Can I recover my WhatsApp account if I forgot my account\'s PIN and security s?',
    'How do I recover my WhatsApp account if I forgot my two-step verification code and lost access to the linked email address?',
    'Can I recover my WhatsApp account if I changed my phone number and forgot to update it in the app?',
    'What should I do if I receive an email or message claiming to be from WhatsApp asking for my account details?',
    'How do I recover my WhatsApp account if I\'m unable to receive the verification code due to network issues?',
    'Can I recover my WhatsApp account if I forgot the password for the linked email address?',
    'What steps should I take if I suspect my WhatsApp account has been compromised and messages are being sent without my knowledge?',
    'How do I recover my WhatsApp account if I accidentally uninstalled the app and lost access to my phone number?',
    'Can I recover my WhatsApp account if I\'m unable to receive the verification code due to being in a different country?',
    'What should I do if I suspect my WhatsApp account has been hacked and my contacts are receiving spam messages from me?',
    'How do I recover my WhatsApp account if I forgot the s to my security s and lost access to my phone number?',
    'How do I recover my WhatsApp account if I forgot my phone number but remember my email address?',
    'Can I recover my WhatsApp account if I deleted the app and lost access to the linked email address?',
    'What should I do if my WhatsApp account is banned due to unauthorized use or violating terms of service?',
    'How do I recover my WhatsApp account if I lost my phone and don\'t have access to any recovery options?',
    'Can I recover my WhatsApp account if I forgot my two-step verification code and don\'t have access to email or phone?',
    'What steps should I take if my WhatsApp account is locked due to suspicious activity?',
    'How do I recover my WhatsApp account if I forgot my PIN and security s?',
    'Can I recover my WhatsApp account if I don\'t remember when I created it?',
    'What should I do if I receive a message or email claiming to be from WhatsApp asking for personal information?',
    'How do I recover my WhatsApp account if I forgot my security s and my phone number is no longer active?',
    'How do I recover my WhatsApp account if I forgot my two-step verification code and don\'t have access to the email or phone number?',
    "What steps should I take if my WhatsApp account is compromised and someone else is using it?",
    "How do I recover my WhatsApp account if I forgot my PIN and security s, and my email is no longer active?",
    "Can I recover my WhatsApp account if I lost access to my phone number and email due to a change in circumstances?",
    "What should I do if my WhatsApp account is banned after being reported by someone mistakenly?",
    "How do I recover my WhatsApp account if I forgot my phone number, email, PIN, and security s?",
    "How do I recover my WhatsApp account if I forgot my phone number and security PIN?",
    "Can I recover my WhatsApp account if I accidentally deleted the app and didn't back up my chats?",
    "What should I do if my WhatsApp account is banned for sharing inappropriate content?",
    "How do I recover my WhatsApp account if I forgot my two-step verification code and security s?",
    "Can I recover my WhatsApp account if I don't have access to the email or phone number linked to it?",
    "What steps should I take if my WhatsApp account is compromised and someone else is using it?",
    "How do I recover my WhatsApp account if I forgot my PIN and security s, and my email is no longer active?",
    "Can I recover my WhatsApp account if I lost access to my phone number and email due to a change in circumstances?",
    "What should I do if my WhatsApp account is banned after being reported by someone mistakenly?",
    "How do I recover my WhatsApp account if I forgot my phone number, email, PIN, and security s?",
    "How do I recover my WhatsApp account if I forgot my phone number and security PIN?",
    "Can I recover my WhatsApp account if I accidentally deleted the app and didn't back up my chats?",
    "What should I do if my WhatsApp account is banned for sharing inappropriate content?",
    "How do I recover my WhatsApp account if I forgot my two-step verification code and security s?",
    "Can I recover my WhatsApp account if I don't have access to the email or phone number linked to it?",
    "What steps should I take if my WhatsApp account is compromised and someone else is using it?",
    "How do I recover my WhatsApp account if I forgot my PIN and security s, and my email is no longer active?",
    "Can I recover my WhatsApp account if I lost access to my phone number and email due to a change in circumstances?",
    "What should I do if my WhatsApp account is banned after being reported by someone mistakenly?",
    "How do I recover my WhatsApp account if I forgot my phone number, email, PIN, and security s?",
    "How do I recover my WhatsApp account if I forgot my phone number and security PIN?",
    "Can I recover my WhatsApp account if I accidentally deleted the app and didn't back up my chats?",
    "What should I do if my WhatsApp account is banned for sharing inappropriate content?",
    "How do I recover my WhatsApp account if I forgot my two-step verification code and security s?",
    "Can I recover my WhatsApp account if I don't have access to the email or phone number linked to it?",
    "What steps should I take if my WhatsApp account is compromised and someone else is using it?",
    "How do I recover my WhatsApp account if I forgot my PIN and security s, and my email is no longer active?",
    "Can I recover my WhatsApp account if I lost access to my phone number and email due to a change in circumstances?",
    "What should I do if my WhatsApp account is banned after being reported by someone mistakenly?",
    "How do I recover my WhatsApp account if I forgot my phone number, email, PIN, and security s?",
    "How do I recover my WhatsApp account if I forgot my phone number and security PIN?",
    "Can I recover my WhatsApp account if I accidentally deleted the app and didn't back up my chats?",
    "What should I do if my WhatsApp account is banned for sharing inappropriate content?",
    "How do I recover my WhatsApp account if I forgot my two-step verification code and security s?",
    "Can I recover my WhatsApp account if I don't have access to the email or phone number linked to it?",
    "What steps should I take if my WhatsApp account is compromised and someone else is using it?",
    "How do I recover my WhatsApp account if I forgot my PIN and security s, and my email is no longer active?",
    "Can I recover my WhatsApp account if I lost access to my phone number and email due to a change in circumstances?",
    "What should I do if my WhatsApp account is banned after being reported by someone mistakenly?",
    "How do I recover my WhatsApp account if I forgot my phone number, email, PIN, and security s?",
    "How do I recover my WhatsApp account if I forgot my phone number and security PIN?",
    "Can I recover my WhatsApp account if I accidentally deleted the app and didn't back up my chats?",
    "What should I do if my WhatsApp account is banned for sharing inappropriate content?",
    "How do I recover my WhatsApp account if I forgot my two-step verification code and security s?",
    "Can I recover my WhatsApp account if I don't have access to the email or phone number linked to it?",
    "What steps should I take if my WhatsApp account is compromised and someone else is using it?",
    "How do I recover my WhatsApp account if I forgot my PIN and security s, and my email is no longer active?",
    "Can I recover my WhatsApp account if I lost access to my phone number and email due to a change in circumstances?",
    "What should I do if my WhatsApp account is banned after being reported by someone mistakenly?",
    "How do I recover my WhatsApp account if I forgot my phone number, email, PIN, and security s?",
    "How do I recover my WhatsApp account if I forgot my phone number and security PIN?",
    "Can I recover my WhatsApp account if I accidentally deleted the app and didn't back up my chats?",
    "What should I do if my WhatsApp account is banned for sharing inappropriate content?",
    "How do I recover my WhatsApp account if I forgot my two-step verification code and security s?",
    "Can I recover my WhatsApp account if I don't have access to the email or phone number linked to it?",
    "What steps should I take if my WhatsApp account is compromised and someone else is using it?",
    "How do I recover my WhatsApp account if I forgot my PIN and security s, and my email is no longer active?",
    "Can I recover my WhatsApp account if I lost access to my phone number and email due to a change in circumstances?",
    "What should I do if my WhatsApp account is banned after being reported by someone mistakenly?",
    "How do I recover my WhatsApp account if I forgot my phone number, email, PIN, and security s?",
    "How do I recover my WhatsApp account if I forgot my phone number and security PIN?",
    "Can I recover my WhatsApp account if I accidentally deleted the app and didn't back up my chats?",
    "How do I recover my Snapchat account if I forgot my security s?",
    "What steps should I take if my Snapchat account has been hacked?",
    "How long does it take for Snapchat support to respond to account recovery requests?",
    "Can I recover my Snapchat account if I no longer have access to the email used for registration?",
    "How do I recover my Snapchat account if I forgot my password and don't have access to the email or phone number?",
    "Can I recover my Snapchat account if I forgot both my username and password?",
    "How do I recover my Snapchat account if I accidentally deleted the app and forgot my login credentials?",
    "What should I do if my Snapchat account is permanently locked?",
    "How can I recover my Snapchat account if my phone number has changed?",
    "Can I recover my Snapchat account if I deactivated it and want to reactivate it later?",
  ];

//   static List<String> getSuggestions(String query) {
//     List<String> matches = [];
//     matches.addAll(suggestionlist);
//     matches.retainWhere((s) => s.toLowerCase().contains(query.toLowerCase()));
//     return matches;
//   }
}
